### ISSUE TITLE
Actual configuration settings URL

### ISSUE THREAD

**Issue by vajlex** [openscholar/pinserver#10]
The Install documentation (Step # 7) says to configure your GPG and Harvard PIN application info at:  
/admin/settings/pinserver

Which presumably should be:  drupal-root/?q=admin/settings/pinserver

But this does not resolve to a page.   Similarly, on the modules page, the "configuration" link resolves to:   drupal-root/?q=admin

Which goes to the main Admin dashboard page.

The actual URL for the settings is here:
drupal-root/?q=admin/config/openscholar/pinserver

In addition, the Install steps #4 and #5 are dead links.

**Comment by Ferdi** [comment]
Thanks @vajlex . This commit http://goo.gl/EY4Mc should fix the issue.
