### ISSUE TITLE
Duplicate module: PIN server module for Drupal 7

### ISSUE THREAD

**Issue by chrowe** [openscholar/pinserver#11]
How does the openscholar pinserver module compare to https://git.huit.harvard.edu/pin-server-module-for-drupal-7

**Comment by Ferdi** [comment]
Not sure.  What are you trying to do ?

**Comment by chrowe** [comment]
We are working on a project for Harvard that is using an unversioned Drupal 6 module called pinserver and we are upgrading the site to Drupal 7. Rather than porting that module to D7 we are looking for an existing module that will work. It seems the this is the most maintained module for authenticating with Harvard's PIN system but just wanted to check.

**Comment by rbran100** [comment]
This is the most up to date that I know of.

**Comment by colans** [comment]
@rbran100: Any idea how this differs from the other one?  Is there a reason for the duplication?

**Comment by rbran100** [comment]
@colans I am not sure.  I don't manage that module that module but it appears to be an old copy without the most recent updates and bugfixes.
